### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by rnelson082** [rnelson082/kicksmarter#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Looks great! Here are some comments:

## Functionality

- [ ] Have the KickSmarter logo be a link to `/`
- [ ] I should not be able to go to `/login` or `/signup` when logged in
- [ ] Refreshing the page should keep me logged in

## Styling

- [ ] Will there be a background image? If so, use a placeholder for now
- [ ] Put the `email` input above `password`
- [ ] The Nav bar and footer text should be bigger
- [ ] The Logout button could use some vertical padding

**Comment by rnelson082** [comment]
think i got it!

**Comment by niartenyaw** [comment]
Awesome! Three small things:

- [ ] When logging in, it does not redirect me to `/`
- [ ] `http://kicksmarter.herokuapp.com/#/vewrvwerb` does not redirect me to `/`
- [ ] The `Logout` button could use more padding

**Comment by rnelson082** [comment]
Hello Aaron - thanks for the quick replies! I appreciate your generous support, especially during your time off! 
I think.... I got it this time! ...? !  Let me know! 
Thanks again.
