### ISSUE TITLE
PA Review: Project Index, Form, Show

### ISSUE THREAD

**Issue by rnelson082** [rnelson082/kicksmarter#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Awesome!

## Functionality

- [ ] It deleted my project when i cancelled :(
![img](https://media3.giphy.com/media/OPU6wzx8JrHna/giphy.gif)

## Style

- [ ] Would add some top padding to the description input box
- [ ] Also the description box is wider than the others

**Comment by rnelson082** [comment]
Thanks Aaron, I will get back to these ASAP!
